### ISSUE TITLE
Offline and unable to make commits 

### ISSUE THREAD

**Issue by JordynD** [JordynD/css-validation-fixes#1]
<img width="535" alt="Screen Shot 2021-03-19 at 1 29 30 AM" src="https://user-images.githubusercontent.com/77690445/111735540-92694380-8852-11eb-9e5a-0210b66d95a9.png">
I am receiving this as my only error and am unable to make any commits for some reason, I was even having trouble making this issue. thanks! @hellachella

**Comment by hellachella** [comment]
Go to the github desktop app, go to preferences menu. Then go to "git" in the sidebar and make sure it has your email address. Github has been arbitrarily changing it.

<img width="958" alt="github desktop wont allow commits" src="https://user-images.githubusercontent.com/10465921/112000417-5b19c180-8af4-11eb-9859-fc0919121c22.png">

**Comment by hellachella** [comment]
It may also be the way you've renamed index.html. There is a glitch with Mac OSX. you have to rename the uppercase `Index.html` to anything else `iggypop.html` for example. Commit and push it. Then rename it to lowercase `index.html` and commit and push.,
